[package]

name = "rpassword"
version = "0.1.3"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
description = "Read passwords in console applications."
license = "Apache-2.0"
homepage = "https://github.com/conradkleinespel/rustastic-password"
repository = "https://github.com/conradkleinespel/rustastic-password"
readme = "README.md"
keywords = ["read", "password", "security", "pass", "getpass"]

[target.i686-apple-darwin.dependencies]
libc = "0.2"
termios = "0.2"
[target.x86_64-apple-darwin.dependencies]
libc = "0.2"
termios = "0.2"
[target.i686-unknown-linux-gnu.dependencies]
libc = "0.2"
termios = "0.2"
[target.x86_64-unknown-linux-gnu.dependencies]
libc = "0.2"
termios = "0.2"
[target.aarch64-unknown-linux-gnu.dependencies]
libc = "0.2"
termios = "0.2"
[target.arm-unknown-linux-gnueabihf.dependencies]
libc = "0.2"
termios = "0.2"
[target.arm-unknown-linux-gnueabi.dependencies]
libc = "0.2"
termios = "0.2"
[target.mipsel-unknown-linux-gnu.dependencies]
libc = "0.2"
termios = "0.2"
[target.mips-unknown-linux-gnu.dependencies]
libc = "0.2"
termios = "0.2"
[target.i686-unknown-linux-musl.dependencies]
libc = "0.2"
termios = "0.2"
[target.x86_64-unknown-linux-musl.dependencies]
libc = "0.2"
termios = "0.2"
[target.mips-unknown-linux-musl.dependencies]
libc = "0.2"
termios = "0.2"
[target.mipsel-unknown-linux-musl.dependencies]
libc = "0.2"
termios = "0.2"
[target.i686-unknown-freebsd.dependencies]
libc = "0.2"
termios = "0.2"
[target.x86_64-unknown-freebsd.dependencies]
libc = "0.2"
termios = "0.2"
[target.x86_64-unknown-dragonfly.dependencies]
libc = "0.2"
termios = "0.2"
[target.i686-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
[target.i686-pc-windows-msvc.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
